export const SUBREDDITS = [
  'AppDevelopers',
  'WebDeveloperJobs',
  'forhire',
  'freelance',
  'Freelancers',
  'slavelabour',
  'Hiring',
  'jobbit',
  'WorkOnline',
  'DoneDirtCheap',
  'startups',
  'SideProject',
  'EntrepreneurRideAlong',
  'cofounder',
  'SaaS',
  'Entrepreneur',
  'NoCode',
  'indiehackers',
  'FlutterDev',
  'ReactNative',
  'androiddev',
  'webdev'
];

export const KEYWORDS = [
  'looking for developer',
  'need developer',
  'need app developer',
  'need mobile developer',
  'need software engineer',
  'need full stack developer',
  'need programmer',
  'looking for flutter developer',
  'looking for react native developer',
  'looking for mobile app developer',
  'looking for software developer',
  'looking for engineer',
  'looking for freelancer',
  'looking for agency',
  'looking for technical partner',
  'looking for cto',
  'technical cofounder',
  'hire flutter developer',
  'hire react native developer',
  'hire app developer',
  'hire mobile developer',
  'hire software engineer',
  'developer wanted',
  'freelancer wanted',
  'agency wanted',
  'contract developer',
  'remote developer',
  'freelance developer',
  'project available',
  'paid project',
  'contract work',
  'hourly work',
  'fixed price',
  'budget',
  'funded',
  'mvp',
  'build app',
  'build mobile app',
  'build saas',
  'build mvp',
  'need mvp',
  'paid work',
  'paid gig',
  'dm me',
  'send portfolio',
  'apply at',
  'cofounder',
  'co-founder',
  'cto',
  'hiring'
];
