export const SUBREDDITS = [
  'AppDevelopers',
  'WebDeveloperJobs',
  'forhire',
  'freelance',
  'Freelancers',
  'slavelabour',
  'Hiring',
  'jobbit',
  'WorkOnline',
  'DoneDirtCheap',
  'startups',
  'SideProject',
  'EntrepreneurRideAlong',
  'cofounder',
  'SaaS',
  'Entrepreneur',
  'NoCode',
  'indiehackers',
  'FlutterDev',
  'ReactNative',
  'androiddev',
  'webdev'
];

export const KEYWORDS = [
  'looking for developer',
  'need developer',
  'need app developer',
  'need mobile developer',
  'need software engineer',
  'need full stack developer',
  'need programmer',
  'looking for flutter developer',
  'looking for react native developer',
  'looking for mobile app developer',
  'looking for software developer',
  'looking for engineer',
  'looking for freelancer',
  'looking for agency',
  'looking for technical partner',
  'looking for cto',
  'technical cofounder',
  'hire flutter developer',
  'hire react native developer',
  'hire app developer',
  'hire mobile developer',
  'hire software engineer',
  'developer wanted',
  'freelancer wanted',
  'agency wanted',
  'contract developer',
  'contractor',
  'remote developer',
  'freelance developer',
  'project available',
  'paid project',
  'contract work',
  'hourly work',
  'fixed price',
  'budget',
  'funded',
  'investment',
  'mvp',
  'prototype',
  'beta',
  'startup',
  'startup app',
  'startup idea',
  'build app',
  'build mobile app',
  'build saas',
  'build mvp',
  'ai app',
  'ai startup',
  'openai app',
  'chatgpt app',
  'flutter',
  'react native',
  'ios',
  'android',
  'swift',
  'kotlin',
  'firebase',
  'supabase',
  'node.js',
  'express',
  'next.js',
  'react',
  'typescript',
  'rest api',
  'graphql',
  'mongodb',
  'postgresql',
  'stripe',
  'paypal',
  'maps',
  'gps',
  'notifications',
  'chat',
  'messaging',
  'marketplace',
  'booking app',
  'food delivery',
  'fitness app',
  'healthcare app',
  'doctor app',
  'hospital app',
  'dating app',
  'social app',
  'crm',
  'erp',
  'inventory',
  'pos',
  'restaurant app',
  'travel app',
  'real estate app',
  'education app',
  'e-learning',
  'fintech',
  'wallet',
  'payment gateway',
  'subscription app',
  'uber clone',
  'airbnb clone',
  'ecommerce app',
  'shopping app',
  'video app',
  'streaming app',
  'music app',
  'photo sharing',
  'dashboard',
  'admin panel',
  'cross platform',
  'native app',
  'hybrid app',
  'app redesign',
  'app maintenance',
  'bug fixing',
  'feature development',
  'app update',
  'launch app',
  'app store',
  'play store',
  'urgent',
  'asap',
  'immediate',
  'ready to start',
  'need today',
  'this week',
  'this month',
  'high priority',
  'long term',
  'short term',
  'agency',
  'consultant',
  'senior flutter',
  'senior react native',
  'senior full stack',
  'senior mobile developer',
  'need team',
  'need freelancer',
  'need agency',
  'scale startup',
  'pre-seed',
  'seed funded',
  'series a',
  'vc backed',
  'bootstrapped',
  'founder',
  'co-founder',
  'indie hacker',
  'saas founder',
  'remote',
  'worldwide',
  'us startup',
  'uk startup',
  'canada startup',
  'australia startup',
  'europe startup'
];
